import {events,essentials,budget,filterEvents,cleanState} from './core.js';
const $=s=>document.querySelector(s),money=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(v),key='rave-radar:v1';
let state;try{state=cleanState(JSON.parse(localStorage.getItem(key)));}catch{state=cleanState(null);}let genre='Todos',toastTimer;
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3000);}
function save(){try{localStorage.setItem(key,JSON.stringify(state));}catch{toast('O navegador não permitiu salvar. Seu plano funciona nesta sessão.');}}
function renderEvents(){const visible=filterEvents(events,genre,$('#search').value);$('#event-count').textContent=`${visible.length} experiências demonstrativas`;$('#events').innerHTML=visible.map(e=>`<article class="event-card"><div class="poster ${e.color}"><span class="poster-tag">${e.tag}</span><button class="favorite" data-favorite="${e.id}" aria-label="Favoritar ${e.name}" aria-pressed="${state.favorites.includes(e.id)}">${state.favorites.includes(e.id)?'♥':'♡'}</button><div class="poster-type">${e.id==='aurora'?'AURORA<br><small>GATHERING</small>':e.id==='subsolo'?'SUBSOLO<br><small>303</small>':'ÓRBITA<br><small>FESTIVAL</small>'}</div><span class="poster-bottom">${e.genre.toUpperCase()} / ${e.hours}</span></div><div class="event-details"><div class="event-meta"><span>${e.genre}</span><time datetime="${e.date}">${new Intl.DateTimeFormat('pt-BR',{day:'2-digit',month:'short',timeZone:'UTC'}).format(new Date(e.date+'T12:00:00Z'))} 2027</time></div><h3>${e.name}</h3><p>↗ ${e.city}</p><div class="event-bottom"><span>A partir de <strong>${money(e.price)}</strong></span><button data-select="${e.id}" aria-label="Planejar ${e.name}">Planejar ↗</button></div></div></article>`).join('')||'<p class="empty">Nenhum evento por aqui. Tente outro nome, cidade ou estilo.</p>';}
$('#events').addEventListener('click',ev=>{const favorite=ev.target.closest('[data-favorite]');if(favorite){const id=favorite.dataset.favorite;state.favorites=state.favorites.includes(id)?state.favorites.filter(x=>x!==id):[...state.favorites,id];save();renderEvents();return;}const select=ev.target.closest('[data-select]');if(select){chooseEvent(select.dataset.select);$('#planner').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});}});
$('.genres').addEventListener('click',ev=>{const b=ev.target.closest('[data-genre]');if(!b)return;genre=b.dataset.genre;document.querySelectorAll('[data-genre]').forEach(el=>{el.classList.toggle('active',el===b);el.setAttribute('aria-pressed',String(el===b));});renderEvents();});$('#search').addEventListener('input',renderEvents);
$('#plan').innerHTML=events.map(e=>`<option value="${e.id}">${e.name} · ${e.city}</option>`).join('');$('#plan').value=state.plan;
function chooseEvent(id){state.plan=id;state.costs.ticket=events.find(e=>e.id===id).price;$('#plan').value=id;$('#budget-form').elements.ticket.value=state.costs.ticket;calculate();toast('Evento selecionado. Ajuste os gastos do seu grupo.');}
$('#plan').addEventListener('change',ev=>chooseEvent(ev.target.value));const form=$('#budget-form');for(const [name,value] of Object.entries(state.costs))form.elements[name].value=value;
function calculate(){if(!form.checkValidity()){$('#budget-error').textContent='Revise os valores. Use de 1 a 100 pessoas e gastos entre R$ 0 e R$ 1.000.000.';$('#per-person').textContent='—';$('#total').textContent='—';return false;}const costs=Object.fromEntries(new FormData(form).entries());try{const result=budget(costs);state.costs=Object.fromEntries(Object.entries(costs).map(([k,v])=>[k,Number(v)]));$('#budget-error').textContent='';$('#per-person').textContent=money(result.perPerson);$('#total').textContent=money(result.total);save();return true;}catch{$('#budget-error').textContent='Confira os valores informados.';return false;}}
form.addEventListener('input',calculate);form.addEventListener('submit',ev=>ev.preventDefault());
function renderChecks(){$('#checks').innerHTML=essentials.map((item,i)=>`<label class="check-row"><input type="checkbox" data-check="${i}" ${state.checked.includes(i)?'checked':''}><span>${item}</span></label>`).join('');$('#check-count').textContent=`${state.checked.length}/${essentials.length}`;$('#progress-fill').style.width=`${state.checked.length/essentials.length*100}%`;$('.progress').setAttribute('aria-valuenow',state.checked.length);}
$('#checks').addEventListener('change',ev=>{const i=Number(ev.target.dataset.check);state.checked=ev.target.checked?[...state.checked,i]:state.checked.filter(x=>x!==i);save();renderChecks();});
$('#export').addEventListener('click',()=>{if(!calculate()){toast('Revise o orçamento antes de exportar.');return;}const event=events.find(e=>e.id===state.plan);const payload={project:'RaveRadar',demo:true,event,costs:state.costs,estimate:budget(state.costs),checklist:essentials.map((item,i)=>({item,done:state.checked.includes(i)})),favorites:state.favorites};const url=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='meu-role-rave-radar.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Plano exportado!');});renderEvents();renderChecks();calculate();
