export const events=[
{id:'aurora',name:'Aurora Gathering',genre:'Psytrance',city:'Uberlândia, MG',date:'2027-05-22',price:180,hours:'18h → 10h',tag:'OPEN AIR',color:'violet'},
{id:'subsolo',name:'Subsolo 303',genre:'Techno',city:'São Paulo, SP',date:'2027-06-12',price:120,hours:'23h → 07h',tag:'WAREHOUSE',color:'lime'},
{id:'orbita',name:'Órbita Festival',genre:'Progressive',city:'Belo Horizonte, MG',date:'2027-07-17',price:240,hours:'16h → 12h',tag:'IMMERSIVE',color:'pink'}
];
export const essentials=['Ingresso e documento','Transporte de ida e volta','Garrafa de água permitida','Protetor auricular','Carregador portátil','Agasalho e capa de chuva','Ponto de encontro com a galera','Regras e horários do evento'];
export function budget({ticket=0,transport=0,food=0,extras=0,people=1}) {const values=[ticket,transport,food,extras,people].map(Number);if(values.some(v=>!Number.isFinite(v)||v<0)||!Number.isInteger(values[4])||values[4]<1||values[4]>100) throw new RangeError('Informe valores positivos e entre 1 e 100 pessoas.');const [t,r,f,e,p]=values;return {perPerson:t+f+(r+e)/p,total:(t+f)*p+r+e};}
export function filterEvents(list,genre,query){const normalize=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();return list.filter(e=>(genre==='Todos'||e.genre===genre)&&normalize(e.name+' '+e.city).includes(normalize(query.trim())));}
export function cleanState(raw){const validIds=new Set(events.map(e=>e.id));return {favorites:Array.isArray(raw?.favorites)?[...new Set(raw.favorites.filter(id=>validIds.has(id)))]:[],checked:Array.isArray(raw?.checked)?[...new Set(raw.checked.filter(i=>Number.isInteger(i)&&i>=0&&i<essentials.length))]:[],plan:validIds.has(raw?.plan)?raw.plan:events[0].id,costs:{ticket:180,transport:160,food:70,extras:40,people:2,...Object.fromEntries(Object.entries(raw?.costs||{}).filter(([k,v])=>['ticket','transport','food','extras','people'].includes(k)&&Number.isFinite(v)&&v>=0&&(k!=='people'||(Number.isInteger(v)&&v>=1&&v<=100))))}};}
